CREATE TABLE stores (
    store INT PRIMARY KEY,
    type VARCHAR(255),
    size INT
);
CREATE TABLE features (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    store INT,
    date DATE,
    temperature FLOAT,
    fuel_price FLOAT,
    cpi FLOAT,
    FOREIGN KEY (store) REFERENCES stores(store)
);
CREATE TABLE Train (
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   store INT,
   dept INT,
   date DATE,
   weekly_sales FLOAT,
   is_holiday BOOLEAN,
   FOREIGN KEY (store) REFERENCES stores(store)
);
